/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.59
 * Generated at: 2022-07-20 04:46:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Styles/Register.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Styles/Header.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/Styles/Footer.css\">\r\n");
      out.write("<script src=\"Scripts/Register.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"Scripts/Deactivate.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<title>Online Event Planning</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"body\">\r\n");
      out.write("\r\n");
      out.write("<!--Header starts-->\r\n");
      out.write("    <header>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <img src=\"./Images/Planning pod.png\" />\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"Login.jsp\">Login</a></li>\r\n");
      out.write("          <li><a href=\"#\">Contact Us</a></li>\r\n");
      out.write("          <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("          <li><a href=\"#\">Services</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("    <!--header ends-->\r\n");
      out.write(" <div>  \r\n");
      out.write("  \r\n");
      out.write("  <div class=\"container1\">\r\n");
      out.write("\r\n");
      out.write("    <form id=\"signup\" name=\"retype\" action=\"registerservlet\" method=\"post\" onsubmit=\"return cal()\" class=\"register-form\" >\r\n");
      out.write("\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("        \r\n");
      out.write("            <center><h3>Sign Up</h3></center>\r\n");
      out.write("            \r\n");
      out.write("        <center> <p>Fill out this form to Register</p></center>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"sep\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"inputs\">\r\n");
      out.write("        \r\n");
      out.write("            <input type=\"text\" placeholder=\"First Name\" name=\"fname\" />\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" placeholder=\"Last Name\" name=\"lname\" />\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" placeholder=\"User Name\" name=\"name\" />\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" placeholder=\"Email\" name=\"email\" required/>\r\n");
      out.write("        \r\n");
      out.write("            <input type=\"password\" placeholder=\"Password\" name=\"password\" id=\"password\" pattern = \".{8,}\" required/>\r\n");
      out.write("\r\n");
      out.write("            <input type=\"password\" placeholder=\"Confirm Password\" name=\"password1\" id=\"repassword\" pattern = \".{8,}\"  />\r\n");
      out.write("\r\n");
      out.write("            <input type=\"text\" placeholder=\"Phone Number\" name=\"phone\" />\r\n");
      out.write("            \r\n");
      out.write("            <center><div class=\"checkbox\">\r\n");
      out.write("            <input type=\"checkbox\"  onclick=\"enable()\"  id=\"box\" required >\r\n");
      out.write("                <!-- <input name=\"check\" id=\"check\" value=\"1\" type=\"checkbox\" /> --><label class=\"terms\">Agreed to terms and conditions</label>\r\n");
      out.write("            </div></center>\r\n");
      out.write("            \r\n");
      out.write("           <!--  <a id=\"submit\" href=\"#\">SIGN UP</a><br> -->\r\n");
      out.write("            <input type=\"submit\" id=\"submit\" value=\"Register\" class=\"btn\"><br>\r\n");
      out.write("\r\n");
      out.write("        <center><label class=\"terms\">Already have an account? <a href=\"Login.jsp\">Login</a></label></center>\r\n");
      out.write("        \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write(" </div>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("<!--footer starts-->\r\n");
      out.write("    <footer style=\"margin-top: 300px;\">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"div_footer\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\">link1</a></li>\r\n");
      out.write("          <li><a href=\"#\">link2</a></li>\r\n");
      out.write("          <li><a href=\"#\">link3</a></li>\r\n");
      out.write("          <li><a href=\"#\">link4</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"div_footer\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\">link1</a></li>\r\n");
      out.write("          <li><a href=\"#\">link2</a></li>\r\n");
      out.write("          <li><a href=\"#\">link3</a></li>\r\n");
      out.write("          <li><a href=\"#\">link4</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"div_footer\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\">link1</a></li>\r\n");
      out.write("          <li><a href=\"#\">link2</a></li>\r\n");
      out.write("          <li><a href=\"#\">link3</a></li>\r\n");
      out.write("          <li><a href=\"#\">link4</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"img_foo\">\r\n");
      out.write("        <div class=\"icons_in_the_footer\">\r\n");
      out.write("          <img src=\"./Images/icons8-facebook-384.png\" />\r\n");
      out.write("          <img src=\"./Images/icons8-instagram-480.png\" />\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"img_foo\">\r\n");
      out.write("        <div class=\"icons_in_the_footer\">\r\n");
      out.write("          <img src=\"./Images/icons8-linkedin-480.png\" />\r\n");
      out.write("          <img src=\"./Images/icons8-reddit-480.png\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"img_foo\">\r\n");
      out.write("        <div class=\"icons_in_the_footer\">\r\n");
      out.write("          <img src=\"./Images/icons8-youtube-480.png\"  />\r\n");
      out.write("          <img src=\"./Images/icons8-twitter-480.png\"  />\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <img\r\n");
      out.write("          class=\"footer_logo\"\r\n");
      out.write("          src=\"./Images/Planning pod white.png\"\r\n");
      out.write("          alt=\"\"\r\n");
      out.write("        />\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!--footer ends-->\r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
